Data Types & Attributes

In [61]:
import numpy as np

In [62]:
# Create a NumPy array arr of integers from 0 to 5 and print its data type.
arr = np.arange(6)
print(arr.dtype)

int32


In [63]:
# Given a NumPy array arr, check if its data type is float64
is_float64 = arr.dtype == np.float64
print(is_float64)

False


In [64]:
# Create a NumPy array arr with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [65]:
# Convert an existing NumPy array arr of integers to float32 data type.
arr = np.array([1, 2, 3])
arr_float = arr.astype(np.float32)
print(arr_float)

[1. 2. 3.]


In [66]:
#Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision
arr = np.array([1.0, 2.0], dtype=np.float64)
arr_reduced = arr.astype(np.float32)
print(arr_reduced)

[1. 2.]


In [67]:
def array_attributes(arr):
  array_shape = arr.shape
  
  array_size = arr.size
  
  array_dtype = arr.dtype

  return array_shape, array_size, array_dtype

# Example Usage:
if __name__ == "__main__":
  # Create a sample NumPy array
  my_array = np.array([[10, 20, 30], [40, 50, 60]], dtype=np.int32)

  # Call the function to get the attributes
  shape, size, dtype = array_attributes(my_array)

  # Print the results
  print(f"Array:\n{my_array}")
  print(f"Shape: {shape}")
  print(f"Size: {size}")
  print(f"Data Type: {dtype}")


Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Size: 6
Data Type: int32


In [68]:
# Create a function array_dimension that returns the dimensionality of a NumPy array.
def array_dimension(a):
    return a.ndim

if __name__ == "__main__":
  # 1D array
  arr_1d = np.array([1, 2, 3, 4, 5])
  print(f"Array: {arr_1d}")
  print(f"Dimensionality: {array_dimension(arr_1d)}")

Array: [1 2 3 4 5]
Dimensionality: 1


In [129]:
# Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.
import numpy as np
def item_size_info(numpy_array):
  if not isinstance(numpy_array, np.ndarray):
    raise TypeError("Input must be a NumPy array.")
  item_size = numpy_array.itemsize
  total_size = numpy_array.nbytes
  return item_size, total_size
    
my_data = np.array([[1.1, 2.2, 3.3],
                    [4.4, 5.5, 6.6]], dtype=np.float32)

print(f"Original Array:\n{my_data}\n")
print(f"Data Type: {my_data.dtype}")
print(f"Shape: {my_data.shape}")
print(f"Number of elements (size): {my_data.size}\n")


Original Array:
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]

Data Type: float32
Shape: (2, 3)
Number of elements (size): 6



In [130]:
# Create a function array_strides that returns the strides of the given NumPy array
def array_strides(a):
    if not isinstance(a, np.ndarray):
        raise TypeError("Input must be a NumPy array.")
    return a.strides

arr_1d = np.array([10, 20, 30, 40], dtype=np.int32)
strides_1d = array_strides(arr_1d)
print(f"--- 1D Array ---")
print(f"Array: {arr_1d}")
print(f"Data type: {arr_1d.dtype}, Item size: {arr_1d.itemsize} bytes")
print(f"Strides: {strides_1d}")


--- 1D Array ---
Array: [10 20 30 40]
Data type: int32, Item size: 4 bytes
Strides: (4,)


In [131]:
# Design a function shape_stride_relationship that returns the shape and strides of the given array.


def shape_stride_relationship(a):
  
  array_shape = a.shape
  
  array_strides = a.strides

  return array_shape, array_strides


arr_1d = np.array([10, 20, 30, 40], dtype=np.int32) # Each int32 is 4 bytes
print(f"--- 1D Array ({arr_1d.dtype}, itemsize={arr_1d.itemsize} bytes) ---")
print(f"Array: {arr_1d}")
shape_1d, strides_1d = shape_stride_relationship(arr_1d)
print(f"Shape: {shape_1d}")
print(f"Strides: {strides_1d}")


--- 1D Array (int32, itemsize=4 bytes) ---
Array: [10 20 30 40]
Shape: (4,)
Strides: (4,)


Array Creations

In [133]:
# Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)
array_1d = create_zeros_array(5)
print(f"1D Array of Zeros:\n{array_1d}\n")
array_2d = create_zeros_array((3, 4))
print(f"2D Array of Zeros (3x4):\n{array_2d}\n")    

1D Array of Zeros:
[0. 0. 0. 0. 0.]

2D Array of Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [135]:
# Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
# Example 1: Create a 2x3 matrix of ones
matrix_2x3 = create_ones_matrix(2, 3)
print(f"2x3 Matrix of Ones:\n{matrix_2x3}\n")

# Example 2: Create a 4x1 matrix (column vector) of ones
matrix_4x1 = create_ones_matrix(4, 1)
print(f"4x1 Matrix (Column Vector) of Ones:\n{matrix_4x1}\n")    

2x3 Matrix of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

4x1 Matrix (Column Vector) of Ones:
[[1.]
 [1.]
 [1.]
 [1.]]



In [138]:
# Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example 1: Integers from 0 up to (but not including) 10, with a step of 1
arr1 = generate_range_array(0, 10, 1)
print(f"Example 1 (0 to 10, step 1): {arr1}\n")

# Example 2: Integers from 5 up to (but not including) 20, with a step of 3
arr2 = generate_range_array(5, 20, 3)
print(f"Example 2 (5 to 20, step 3): {arr2}\n")

Example 1 (0 to 10, step 1): [0 1 2 3 4 5 6 7 8 9]

Example 2 (5 to 20, step 3): [ 5  8 11 14 17]



In [139]:
# Design a function generate_linear_space(start, stop, num) for equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example 1: Generate 5 evenly spaced numbers between 0 and 10 (inclusive)
arr1 = generate_linear_space(0, 10, 5)
print(f"Example 1 (0 to 10, 5 samples): {arr1}\n")

# Example 2: Generate 7 evenly spaced numbers between -5 and 5 (inclusive)
arr2 = generate_linear_space(-5, 5, 7)
print(f"Example 2 (-5 to 5, 7 samples): {arr2}\n")


Example 1 (0 to 10, 5 samples): [ 0.   2.5  5.   7.5 10. ]

Example 2 (-5 to 5, 7 samples): [-5.         -3.33333333 -1.66666667  0.          1.66666667  3.33333333
  5.        ]



In [137]:
# Create a function create_identity_matrix(n) using numpy.eye
def create_identity_matrix(n):
    return np.eye(n)
# Example 1: Create a 3x3 identity matrix
identity_3x3 = create_identity_matrix(3)
print(f"3x3 Identity Matrix:\n{identity_3x3}\n")

# Example 2: Create a 5x5 identity matrix
identity_5x5 = create_identity_matrix(5)
print(f"5x5 Identity Matrix:\n{identity_5x5}\n")


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [140]:
# Write a function that converts a Python list into a NumPy array
def list_to_array(lst):
    return np.array(lst)

# Example 1: Convert a 1D Python list to a NumPy array
my_list_1d = [1, 2, 3, 4, 5]
numpy_array_1d = list_to_array(my_list_1d)
print(f"Original Python List (1D): {my_list_1d}")
print(f"Converted NumPy Array (1D):\n{numpy_array_1d}")
print(f"Type of converted array: {type(numpy_array_1d)}\n")


Original Python List (1D): [1, 2, 3, 4, 5]
Converted NumPy Array (1D):
[1 2 3 4 5]
Type of converted array: <class 'numpy.ndarray'>



In [78]:
# Create a NumPy array and use numpy.view() to create a new view with the same data.
arr = np.array([1, 2, 3])
view = arr.view()
print(view)

[1 2 3]


Concatenation and Stacking

In [141]:
# Write a function to concatenate two NumPy arrays along a specified axis.
def concatenate_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])
print(f"--- Concatenating 1D Arrays ---")
print(f"Array 1: {arr1_1d}")
print(f"Array 2: {arr2_1d}")
concatenated_1d = concatenate_arrays(arr1_1d, arr2_1d)
print(f"Concatenated (default axis=0): {concatenated_1d}\n")

--- Concatenating 1D Arrays ---
Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated (default axis=0): [1 2 3 4 5 6]



In [80]:
# Concatenate two arrays with different shapes horizontally using numpy.concatenate.
arr1 = np.array([[1], [2]])
arr2 = np.array([[3, 4]])
horizontal_concat = np.concatenate((arr1, arr2.T), axis=1)
print(horizontal_concat)

[[1 3]
 [2 4]]


In [142]:
# Vertically stack multiple arrays from a list using numpy.vstack
def vertical_stack(arrays):
    return np.vstack(arrays)

# Example 1: Vertically stack 1D arrays
arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])
print(f"--- Vertically Stacking 1D Arrays ---")
print(f"Array 1: {arr1_1d}")
print(f"Array 2: {arr2_1d}")
stacked_1d = vertical_stack((arr1_1d, arr2_1d))
print(f"Vertically Stacked Array:\n{stacked_1d}\n")

--- Vertically Stacking 1D Arrays ---
Array 1: [1 2 3]
Array 2: [4 5 6]
Vertically Stacked Array:
[[1 2 3]
 [4 5 6]]



 Array Generation


In [144]:
# Write a function to generate an array of integers within a specified range (inclusive) with a step.
def generate_integer_array(start, stop, step):
    return np.arange(start, stop+1, step)

# Example 1: Integers from 1 to 10 (inclusive), with a step of 1
arr1 = generate_integer_array(1, 10, 1)
print(arr1)



[ 1  2  3  4  5  6  7  8  9 10]


In [83]:
# Generate 10 equally spaced values between 0 and 1 using NumPy.
lin_vals = np.linspace(0, 1, 10)
print(lin_vals)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [84]:
# Create 5 logarithmically spaced values between 1 and 1000.
log_vals = np.logspace(0, 3, 5)
print(log_vals)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Pandas + NumPy

In [85]:
import pandas as pd

In [86]:
# Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1-100).
arr = np.random.randint(1, 101, (5, 3))
df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)

    A   B   C
0  67  61  57
1  78  61  77
2  51  83  81
3  50  50  21
4  80   6  71


In [147]:
# Write a function to replace all negative values in a specific column with zeros using NumPy.
def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df
# 1. Create a sample Pandas DataFrame
data = {
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Sales': [100, -20, 150, -5, 80],
    'Profit': [20, 5, -10, 12, -3]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\n" + "="*30 + "\n")
print("DataFrame after replacing negative 'Sales' with zero:")
df_sales_fixed = replace_negatives_with_zero(df.copy(), 'Sales') # Use .copy() to avoid modifying original df
print(df_sales_fixed)
print("\n" + "="*30 + "\n")
print("DataFrame after replacing negative 'Profit' with zero:")
df_profit_fixed = replace_negatives_with_zero(df.copy(), 'Profit') # Use .copy() to avoid modifying original df
print(df_profit_fixed)
print("\n" + "="*30 + "\n")

Original DataFrame:
  Product  Sales  Profit
0       A    100      20
1       B    -20       5
2       C    150     -10
3       D     -5      12
4       E     80      -3


DataFrame after replacing negative 'Sales' with zero:
  Product  Sales  Profit
0       A    100      20
1       B      0       5
2       C    150     -10
3       D      0      12
4       E     80      -3


DataFrame after replacing negative 'Profit' with zero:
  Product  Sales  Profit
0       A    100      20
1       B    -20       5
2       C    150       0
3       D     -5      12
4       E     80       0




Indexing and Slicing

In [88]:
# Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40])
element = arr[2]
print(element)

30


In [89]:
# Retrieve the element at index (1, 2) from a 2D array.
arr2d = np.array([[1,2,3],[4,5,6]])
element = arr2d[1,2]
print(element)

6


In [90]:
#Extract elements greater than 5 using boolean indexing. 
arr = np.array([1, 6, 8, 3])
elements = arr[arr > 5]
print(element)

6


In [91]:
# Slice elements from index 2 to 5 (inclusive) from a NumPy array
arr = np.arange(10)
slice_ = arr[2:6]
print(slice_)

[2 3 4 5]


In [92]:
# Slice the sub-array [[2, 3], [5, 6]] from a 2D array.
arr2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
sub_array = arr2d[[0,1],[2,2]]
print(sub_array)

[2 5]


Advanced Indexing

In [93]:
# Extract elements based on indices from a 2D array.
arr2d = np.array([[1,2],[3,4]])
indices = [(0,1),(1,0)]
elements = [arr2d[i,j] for i,j in indices]
print(elements)

[2, 3]


In [94]:
# Filter elements greater than a threshold using boolean indexing.
arr = np.array([4,7,1,9])
filtered = arr[arr > 5]
print(filtered)

[7 9]


In [95]:
# Extract specific elements from a 3D array using separate index arrays
arr3d = np.random.randint(10, size=(2,3,4))
ix = [0,1]
jx = [1,2]
kx = [2,3]
elements = arr3d[ix, jx, kx]
print(elements)

[5 5]


In [96]:
# Return elements satisfying two boolean conditions.
arr = np.array([2, 4, 6, 8])
elements = arr[(arr > 3) & (arr < 8)]
print(elements)

[4 6]


In [97]:
# Extract elements from a 2D array using separate row and column index arrays.
arr2d = np.array([[10,20],[30,40]])
rows = np.array([0,1])
cols = np.array([1,0])
elements = arr2d[rows, cols]
print(elements)

[20 30]


Broadcasting

In [98]:
# Add scalar 5 to every element of an array using broadcasting
arr = np.array([1,2,3])
arr += 5
print(arr)

[6 7 8]


In [99]:
# Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.
arr = np.ones((3,4))
mult = np.array([[1],[2],[3]])
result = arr * mult
print(result)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [100]:
# Add a (1, 4) array to every row of a (4, 3) array using broadcasting.
a = np.ones((4,3))
b = np.ones((1,3))
result = a + b
print(result)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [101]:
# Add two arrays of shapes (3, 1) and (1, 3) using broadcasting
a = np.ones((3,1))
b = np.ones((1,3))
result = a + b
print(result)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [102]:
# Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays.
try:
    a = np.ones((2,3))
    b = np.ones((2,2))
    result = a * b
except ValueError as e:
    result = str(e)


 Aggregations and Statistics

In [103]:
# Calculate column-wise mean of a 2D array
arr = np.array([[1,2],[3,4]])
col_mean = arr.mean(axis=0)
print(col_mean)

[2. 3.]


In [104]:
# Find maximum value in each row.
arr = np.array([[1,2],[3,4]])
row_max = arr.max(axis=1)
print(row_max)

[2 4]


In [105]:
# Find indices of maximum values in each column.
arr = np.array([[1,2],[3,4]])
max_idx = arr.argmax(axis=0)
print(max_idx)

[1 1]


In [151]:
# Apply a custom function to compute moving sum along rows.
def moving_sum(arr, k):
    return np.convolve(arr, np.ones(k), 'valid')

data1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
k1 = 3
result1 = moving_sum(data1, k1)
print(result1)

[ 6.  9. 12. 15. 18. 21. 24. 27.]


In [107]:
# Check if all elements in each column are even.
arr = np.array([[2,4],[6,8]])
all_even = (arr % 2 == 0).all(axis=0)
print(all_even)

[ True  True]


Reshaping and Flattening

In [108]:
# Reshape a given array into dimensions m x n.
arr = np.arange(6)
reshaped = arr.reshape(2,3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [109]:
# Return a flattened version of a given matrix
arr = np.arange(6)
flattened = arr.flatten()
print(flattened)

[0 1 2 3 4 5]


In [110]:
# Concatenate two arrays along a specified axis.
arr1 = np.array([[1,2]])
arr2 = np.array([[3,4]])
concat = np.concatenate((arr1, arr2), axis=0)
print(concat)

[[1 2]
 [3 4]]


In [111]:
# Split an array into sub-arrays along a specified axis.
arr = np.array([1,2,3,4,5,6])
splits = np.split(arr, 3)
print(splits)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [112]:
# Insert and delete elements at specified indices from an array.
arr = np.array([1,2,3])
arr_ins = np.insert(arr, 1, 9)
arr_del = np.delete(arr, 2)
print(arr_ins)
print(arr_del)

[1 9 2 3]
[1 2]


Element Operations

In [113]:
# Perform element-wise addition between two arrays.
#  Perform element-wise subtraction: subtract arr2 from arr1.
#  Perform element-wise multiplication.
# Divide elements of arr1 by arr2 element-wise.
# Perform element-wise exponentiation: arr1 ** arr2.
arr1 = np.array([1,2])
arr2 = np.array([3,4])
add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2
exp = arr1 ** arr2
print(add)
print(sub)
print(mul)
print(div)
print(exp)

[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]
[ 1 16]


String Operations

In [114]:
# count occurrences of a substring in a string array.
arr = np.array(['apple', 'banana'])
count = np.char.count(arr, 'a')
print(count)

[1 3]


In [156]:
# Extract uppercase characters from a string array.
import numpy as np

arr = np.array(['Hello World', 'NUMPY is Awesome', 'pyTHON'])

uppercase_chars_list = []

for s in arr:
    current_string_uppercase = []
    for char in s:
        # Check if the character is an uppercase letter
        if 'A' <= char <= 'Z': 
            current_string_uppercase.append(char)
    uppercase_chars_list.append(current_string_uppercase)
uppercase_chars = np.array(uppercase_chars_list, dtype=object)


print(f"Original Array: {arr}")
print({uppercase_chars}")

Original Array: ['Hello World' 'NUMPY is Awesome' 'pyTHON']
Uppercase Chars (without findall): [list(['H', 'W']) list(['N', 'U', 'M', 'P', 'Y', 'A'])
 list(['T', 'H', 'O', 'N'])]


In [116]:
# Replace substring occurrences with another string in a string array.
arr = np.array(['hello', 'world'])
replaced = np.char.replace(arr, 'o', '0')
print(replaced)

['hell0' 'w0rld']


In [117]:
# Concatenate strings in a NumPy array element-wise.
arr1 = np.array(['a','b'])
arr2 = np.array(['x','y'])
concat = np.char.add(arr1, arr2)
print(concat)

['ax' 'by']


In [118]:
# Find the length of the longest string in a string array
arr = np.array(['hi','hello'])
lengths = np.char.str_len(arr)
max_len = lengths.max()
print(max_len)

5


Descriptive Statistics

In [119]:
# Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.
arr = np.random.randint(1,1001,100)
mean = arr.mean()
median = np.median(arr)
var = arr.var()
std = arr.std()
arr = np.random.randint(1,1001,100)
mean = arr.mean()
median = np.median(arr)
var = arr.var()
std = arr.std()
print(mean)
print(var)
print(median)
print(std)


465.26
86112.9324
467.5
293.4500509456422


In [120]:
# Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
arr = np.random.randint(1,101,50)
p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)
print(p25)
print(p75)

21.5
82.0


In [121]:
# Compute correlation coefficient between two arrays using np.corrcoef.
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
corr = np.corrcoef(arr1, arr2)
print(corr)

[[ 1.         -0.21748602]
 [-0.21748602  1.        ]]


In [122]:
# Perform matrix multiplication using np.dot.
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[2,0],[1,2]])
dot = np.dot(arr1, arr2)
print(dot)

[[ 4  4]
 [10  8]]


In [123]:
# Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.
arr = np.random.randint(1,100,50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
print(p10)
print(p50)
print(p90)

20.700000000000003
48.0
88.0


Search and Sort

In [124]:
# Find index of a specific element in an array.
arr = np.array([10, 20, 30])
index = np.where(arr == 20)[0][0]
print(index)

1


In [125]:
# Sort a random array in ascending order.
arr = np.random.rand(5)
sorted_arr = np.sort(arr)
print(sorted_arr)

[0.44264357 0.63078304 0.86131299 0.88271226 0.90891051]


In [126]:
# Filter elements greater than 20.
# Filter elements divisible by 3.
# Filter elements between 20 and 40 (inclusive).
arr = np.arange(50)
filtered1 = arr[arr > 20]
filtered2 = arr[arr % 3 == 0]
filtered3 = arr[(arr >= 20) & (arr <= 40)]
print(filtered1)
print(filtered2)
print(filtered3)

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


Byte Order & Swapping

In [127]:
# Check byte order of a NumPy array using dtype.byteorder
arr = np.array([1,2,3], dtype='>i4')
byte_order = arr.dtype.byteorder
print(byte_order)

>


In [128]:
# Perform in-place byte swapping using byteswap().
arr = np.array([1,2,3], dtype='>i4')
result = arr.byteswap(inplace=True)
print(result)

[16777216 33554432 50331648]
